 * Serving Flask app 'cpi_app.app:create_app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 559-695-107
127.0.0.1 - - [16/Sep/2025 22:29:26] "[35m[1mGET / HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/bjornlevi/projects/CPI/.venv/lib/python3.12/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bjornlevi/projects/CPI/.venv/lib/python3.12/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bjornlevi/projects/CPI/.venv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bjornlevi/projects/CPI/.venv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bjornlevi/projects/CPI/.venv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bjornlevi/projects/CPI/.venv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bjornlevi/projects/CPI/cpi_app/app.py", line 21, in index
    run_id = request.args.get("run_id", type=int)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'request' is not defined
127.0.0.1 - - [16/Sep/2025 22:29:26] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2025 22:29:26] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2025 22:29:27] "GET /?__debugger__=yes&cmd=resource&f=console.png&s=8OHF5giT8ptqkpGif1F1 HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2025 22:29:27] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Detected change in '/home/bjornlevi/projects/CPI/cpi_app/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 559-695-107
127.0.0.1 - - [16/Sep/2025 22:30:21] "[35m[1mGET / HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/bjornlevi/projects/CPI/.venv/lib/python3.12/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bjornlevi/projects/CPI/.venv/lib/python3.12/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bjornlevi/projects/CPI/.venv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bjornlevi/projects/CPI/.venv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bjornlevi/projects/CPI/.venv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bjornlevi/projects/CPI/.venv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bjornlevi/projects/CPI/cpi_app/app.py", line 21, in index
    run_id = request.args.get("run_id", type=int)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'request' is not defined. Did you mean: 'requests'?
127.0.0.1 - - [16/Sep/2025 22:30:21] "[36mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2025 22:30:21] "[36mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2025 22:30:21] "GET /?__debugger__=yes&cmd=resource&f=console.png&s=8IMzYb6wSRpKkcu9QVW9 HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2025 22:30:21] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
 * Detected change in '/home/bjornlevi/projects/CPI/cpi_app/app.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "/home/bjornlevi/projects/CPI/.venv/lib/python3.12/site-packages/flask/cli.py", line 963, in run_command
    app: WSGIApplication = info.load_app()  # pyright: ignore
                           ^^^^^^^^^^^^^^^
  File "/home/bjornlevi/projects/CPI/.venv/lib/python3.12/site-packages/flask/cli.py", line 349, in load_app
    app = locate_app(import_name, name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bjornlevi/projects/CPI/.venv/lib/python3.12/site-packages/flask/cli.py", line 250, in locate_app
    raise NoAppException(
flask.cli.NoAppException: While importing 'cpi_app.app', an ImportError was raised:

Traceback (most recent call last):
  File "/home/bjornlevi/projects/CPI/.venv/lib/python3.12/site-packages/flask/cli.py", line 245, in locate_app
    __import__(module_name)
  File "/home/bjornlevi/projects/CPI/cpi_app/app.py", line 1, in <module>
    import os, request
ModuleNotFoundError: No module named 'request'

 * Debugger is active!
 * Debugger PIN: 610-647-018
127.0.0.1 - - [16/Sep/2025 22:30:48] "[35m[1mGET / HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/bjornlevi/projects/CPI/.venv/lib/python3.12/site-packages/flask/cli.py", line 974, in app
    raise err from None
  File "/home/bjornlevi/projects/CPI/.venv/lib/python3.12/site-packages/flask/cli.py", line 963, in run_command
    app: WSGIApplication = info.load_app()  # pyright: ignore
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bjornlevi/projects/CPI/.venv/lib/python3.12/site-packages/flask/cli.py", line 349, in load_app
    app = locate_app(import_name, name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bjornlevi/projects/CPI/.venv/lib/python3.12/site-packages/flask/cli.py", line 250, in locate_app
    raise NoAppException(
flask.cli.NoAppException: While importing 'cpi_app.app', an ImportError was raised:

Traceback (most recent call last):
  File "/home/bjornlevi/projects/CPI/.venv/lib/python3.12/site-packages/flask/cli.py", line 245, in locate_app
    __import__(module_name)
  File "/home/bjornlevi/projects/CPI/cpi_app/app.py", line 1, in <module>
    import os, request
ModuleNotFoundError: No module named 'request'

127.0.0.1 - - [16/Sep/2025 22:30:48] "[36mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2025 22:30:48] "[36mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2025 22:30:48] "GET /?__debugger__=yes&cmd=resource&f=console.png&s=T5ihgYUrFy3TLm00yysP HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2025 22:30:48] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
 * Detected change in '/home/bjornlevi/projects/CPI/cpi_app/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 559-695-107
127.0.0.1 - - [16/Sep/2025 22:31:23] "[35m[1mGET / HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/bjornlevi/projects/CPI/.venv/lib/python3.12/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bjornlevi/projects/CPI/.venv/lib/python3.12/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bjornlevi/projects/CPI/.venv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bjornlevi/projects/CPI/.venv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bjornlevi/projects/CPI/.venv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bjornlevi/projects/CPI/.venv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bjornlevi/projects/CPI/cpi_app/app.py", line 21, in index
    run_id = requests.args.get("run_id", type=int)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'requests' has no attribute 'args'
127.0.0.1 - - [16/Sep/2025 22:31:23] "[36mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2025 22:31:23] "[36mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2025 22:31:23] "GET /?__debugger__=yes&cmd=resource&f=console.png&s=PyqdazzXZUjf010iGomy HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2025 22:31:23] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
 * Detected change in '/home/bjornlevi/projects/CPI/cpi_app/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 559-695-107
127.0.0.1 - - [16/Sep/2025 22:33:00] "[35m[1mGET / HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/bjornlevi/projects/CPI/.venv/lib/python3.12/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bjornlevi/projects/CPI/.venv/lib/python3.12/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bjornlevi/projects/CPI/.venv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bjornlevi/projects/CPI/.venv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bjornlevi/projects/CPI/.venv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bjornlevi/projects/CPI/.venv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bjornlevi/projects/CPI/cpi_app/app.py", line 35, in index
    cpi_labels = [a.date.strftime("%Y-%m") for a in cpi_actuals[-24:]]
                                                    ^^^^^^^^^^^^^^^^^^
NameError: name 'cpi_actuals' is not defined
127.0.0.1 - - [16/Sep/2025 22:33:00] "[36mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2025 22:33:00] "[36mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2025 22:33:00] "GET /?__debugger__=yes&cmd=resource&f=console.png&s=0GYUhAh4O2rsdTWBhiTb HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2025 22:33:00] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2025 22:33:02] "[35m[1mGET / HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/bjornlevi/projects/CPI/.venv/lib/python3.12/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bjornlevi/projects/CPI/.venv/lib/python3.12/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bjornlevi/projects/CPI/.venv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bjornlevi/projects/CPI/.venv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bjornlevi/projects/CPI/.venv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bjornlevi/projects/CPI/.venv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bjornlevi/projects/CPI/cpi_app/app.py", line 35, in index
    cpi_labels = [a.date.strftime("%Y-%m") for a in cpi_actuals[-24:]]
                                                    ^^^^^^^^^^^^^^^^^^
NameError: name 'cpi_actuals' is not defined
127.0.0.1 - - [16/Sep/2025 22:33:02] "[36mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2025 22:33:02] "[36mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2025 22:33:02] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png&s=0GYUhAh4O2rsdTWBhiTb HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2025 22:33:02] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
 * Detected change in '/home/bjornlevi/projects/CPI/cpi_app/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 559-695-107
 * Detected change in '/home/bjornlevi/projects/CPI/cpi_app/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 559-695-107
 * Detected change in '/home/bjornlevi/projects/CPI/cpi_app/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 559-695-107
127.0.0.1 - - [16/Sep/2025 22:33:56] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2025 22:33:56] "GET /static/app.css HTTP/1.1" 200 -
 * Detected change in '/home/bjornlevi/projects/CPI/cpi_app/app.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "/home/bjornlevi/projects/CPI/.venv/lib/python3.12/site-packages/flask/cli.py", line 963, in run_command
    app: WSGIApplication = info.load_app()  # pyright: ignore
                           ^^^^^^^^^^^^^^^
  File "/home/bjornlevi/projects/CPI/.venv/lib/python3.12/site-packages/flask/cli.py", line 349, in load_app
    app = locate_app(import_name, name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bjornlevi/projects/CPI/.venv/lib/python3.12/site-packages/flask/cli.py", line 245, in locate_app
    __import__(module_name)
  File "/home/bjornlevi/projects/CPI/cpi_app/app.py", line 24, in <module>
    @app.get("/")
     ^^^
NameError: name 'app' is not defined
 * Debugger is active!
 * Debugger PIN: 610-647-018
 * Detected change in '/home/bjornlevi/projects/CPI/cpi_app/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 559-695-107
127.0.0.1 - - [16/Sep/2025 22:38:56] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2025 22:38:56] "[36mGET /static/app.css HTTP/1.1[0m" 304 -
 * Detected change in '/home/bjornlevi/projects/CPI/cpi_app/pipelines/cpi.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 559-695-107
 * Detected change in '/home/bjornlevi/projects/CPI/cpi_app/pipelines/wages.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 559-695-107
 * Detected change in '/home/bjornlevi/projects/CPI/cpi_app/pipelines/wages.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 559-695-107
127.0.0.1 - - [16/Sep/2025 22:41:43] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2025 22:41:43] "[36mGET /static/app.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2025 22:43:49] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2025 22:43:49] "[36mGET /static/app.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2025 22:46:21] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2025 22:46:21] "[36mGET /static/app.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [16/Sep/2025 22:49:18] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2025 22:49:18] "[36mGET /static/app.css HTTP/1.1[0m" 304 -
